layout_spectrum: 0.1052632
typography_spectrum: 0.5150376
color:
  saturation: 0.1648516
  lightness: 0.2644208
  brandStrength: 0.7409324
  rhythmicContrast: 0.9621055
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
name: Peru
